### ISSUE TITLE
More information on downloading the data from the open parallel corpus and also the scripts/text_only_preprocessing.sh file is missing.

### ISSUE THREAD

**Issue by darshanCVIT** [MatthieuFP/VGAMT#1]
Hi Matthieu,
Thank you for your great work. I was reading through the downloading and pre-processing of Text-only data [https://github.com/MatthieuFP/VGAMT/blob/main/data/README.md#text-only-data](https://github.com/MatthieuFP/VGAMT/blob/main/data/README.md#text-only-data). However, I am not sure what exactly to download from the [https://opus.nlpl.eu/](https://opus.nlpl.eu/) website. It would be very helpful if you could provide more information on this as there are a lot of different corpora available.
Also, in the script that you have provided to pre-process the text-only data, the `scripts/text_only_preprocessing.sh` is missing.
Thanks.

**Comment by MatthieuFP** [comment]
Hi Darshan,

Thank you very much for your interest in our work and for pointing out missing information. I plan to update the README.md file (and the git project in general) in the following days to add more details.
- In this project, we used OpenSubtitles_v2018, Books_v1 (not available in cs), Wikipedia_v1.0, TED2020_v1 and TED2013_v1.1 (not available in cs).
- `scripts/text_only_preprocessing.sh` is in `./data` folder. I will clarify this in a future version.

Best regards,
Matthieu

**Comment by darshanCVIT** [comment]
Thanks for the clarification, Matthieu. I will be closing this issue.
