### ISSUE TITLE
MDETR feature extraction

### ISSUE THREAD

**Issue by ZhishenYang** [MatthieuFP/VGAMT#2]
Hi Matthieu,
Thank you for providing the code. I attempted to utilize mdetr_features_extraction.py to extract MDETR features.

The MDETR model output includes the following keys:
dict_keys(['pred_logits,' 'pred_boxes,' 'proj_queries,' 'proj_tokens,' 'tokenized']), but it does not include 'last_hidden_states.'

Error (at line 128):
        last_hidden_states = outputs["last_hidden_states"].cpu()[0, keep].numpy

I would greatly appreciate it if you could guide me on obtaining the last hidden states.
Thanks

**Comment by MatthieuFP** [comment]
Hi,

Thanks for pointing out this bug. During experiments we tried using last hidden states but we ultimately used the proj queries as MDETR features. I will update mdetr_features_extraction.py in the next few days to solve the bug. Meanwhile you can simply ignore or comment the lines related to last_hidden_states. Sorry for that, I'll keep track if this causes subsequent bugs (but I don't think so).

Please let me know if you have any other question,
Best,
Matthieu

**Comment by ZhishenYang** [comment]
Thank you, Matthieu. I will close this issue.
